version: "2.1"
services:
  angular:
    container_name: weekendplanning-app-front
    image: weekendplanning-front
    ports:
      - "4200:4200"
    networks:
      - weekend-network
  mysql:
    container_name: weekendplanning-mysql
    image: mysql
    volumes:
      - /media/www-dev/public/weekendplanning/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weekend-network
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=weekendplanning
      - MYSQL_USER=weekendplanningadmin
      - MYSQL_PASSWORD=weekendplanningadmin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  nginx:
    container_name: weekendplanning-app-nginx
    image: weekendplanning-nginx
    ports:
      - "8080:80"
    networks:
      - weekend-network
          # Map Nginx port 80 to the local machine's port 80

    command: /bin/bash -c "nginx -g 'daemon off;'"

  spring:
    container_name: weekendplanning-app-back
    image: weekendplanning-back

    networks:
          - weekend-network

    depends_on:
      - mysql
networks:
  weekend-network:
    external: true
