version: "2.1"
services:


  mysql:
    container_name: weekendplanning-mysql
    image: mysql
    volumes:
      - /media/www-dev/public/weekendplanning/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weekend-network
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=weekendplanning
      - MYSQL_USER=weekendplanningadmin
      - MYSQL_PASSWORD=weekendplanningadmin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  spring:
    container_name: weekendplanning-app-back
    image: weekendplanning-back
    ports:
      - "8080:8080"
    networks:
      - weekend-network

    depends_on:
      - mysql

networks:
  weekend-network:
    external: true
